### PR TITLE
competitions: Fix for reaching seasons and discussions when no competition is assigned to current site (throw 404)

### PR DESCRIPTION
**Pull request by rtrembecky**
sorry for inconsistencies with merges and commits

### CODE REVIEW

**Comment by rtrembecky** [comment]
Fixes #22 btw

**Comment by tbabej** [comment]
This is looking good, can you please rebase the fix on top of current master?

**Comment by rtrembecky** [comment]
Done.

**Comment by tbabej** [comment]
Thanks!

**Pull request merged**
