### PR TITLE
templates: Add link to "Regulations" static page in menu

### PR DESCRIPTION
**Pull request by rtrembecky**

### CODE REVIEW

**Comment by tbabej** [comment]
This is looking good, however, it's not entirely general - the <a> tag contains a direct reference to our webpage. There is already a precedens in the form of "/sk/zdruzenie/onas/" link, we should remove that too.

As to how to get rid of this - I would suggest introducing a mechanism to include custom links in the menu. As far as I see it, we have three options:

1.) Create an subtemplate file with custom links, which would be then included via the include template tag (an empty version would live in templates_custom.in, e.g. templates_custom/base/menu_custom_links.html). However, to add custom links to different sections of the menu, we would need to introduce multiple custom subtemplates.

2.) Rename the current menu.html to menu_base.html that will define several {% block "custom_links" %} sections, that will enable the users to extend the menu easily. The menu itself would not be in the repo, reference implementation would live in templates_custom/base/menu.html - just as we currently do with the most basic template - templates_custom/base/base.html.

3.) Menu links are pretty structural, so maybe we could define some setting variable for it and generate it dynamically. Seems like an antipattern though..

Thoughts?

**Comment by tbabej** [comment]
After some thought, probably (2) is the best option both for the re-usability and cleanness of the implementation.

**Comment by tbabej** [comment]
Any updates on this?

**Comment by rtrembecky** [comment]
Had it opened for some time but just couldn't get to it. However I agree (2) is the best option; maybe I find myself some time to rework it.

**Pull request closed without merging**
